package main

import "fmt"

func main() {
	fmt.Println("Hello world")
	PrintVariables()
	fmt.Println()
	VariableScope()
	fmt.Println()
	UserInput()
	fmt.Println()
	VariableType()
	fmt.Println()
	typeCasting()
	fmt.Println()
	constants()
	fmt.Println()
	operators()
	fmt.Println()
	controlFlow()
	fmt.Println()
	switchBlock()
	fmt.Println()
	ForLoop()
	fmt.Println()
	Arrays()
	fmt.Println()
	Slices()
	fmt.Println()
	maps()
	fmt.Println()
	fmt.Println("Sum = ", functions(2, 3))
	fmt.Println()
	VariadicFunction("Chandana")
	VariadicFunction("Chandana", "English")
	VariadicFunction("Chandana", "English", "Hindi")
	VariadicFunction("Chandana", "English", "Maths", "Science")
	fmt.Println(factorial(5))
	fmt.Println()
	Pointers()
	fmt.Println()
	Structs()

}
